Project Proposal for EL6383
===========================


## Project idea

Write a 1-2 paragraph summary of your project. Your summary should describe:

* What topic in high speed networks is your project related to? (Your topic should be *substantially* different from the prepared labs you've already completed - "Performance of different TCP variants over networks with a high BDP" is not an acceptable topic, for example.)

* What is the goal of your experiment? Make sure to follow best practices
for setting an experiment goal, as we've discussed in class.

Be as *specific* as you can. You should have a narrow goal that dictates
a particular experiment design, not a broad open-ended evaluation.

You only have a few weeks for this project; set a realistic goal.

-. Our project is related to Routing.Our goal is to measure the processing capability of the following routers, 
1.XORP 
2.OVS(local flow)
3.Linux router
## Experiment design

Describe your experiment design, including the following details (refer to lab slides for more information):

* What is the service you are going to study?
-The processing speed of the aforementioned routers.

* What metric(s) will you measure?
-We will measure packet processing time for each  packet by the router.

* What parameter(s) will you vary? In what range?
-We will vary the tye of routers and measure packet processing time for each kind of router.

* Describe the configuration of your experiment setting (e.g. network environment).
What kind of "real" setting is this meant to represent? How do you know this experiment setting is representative? In what ways is your experiment setting *not* representative?
We will have two host connected through a router.Packets generated by host 1 for host 2 will be captured by router and we will measure the processing time.As we  are comparing performance of different routers
based on their processing time,at the end of our experiment we will the fastest router among the metioned routers.Since we are using a very basic algorithm for scheduling,it is not representative of 
performance of routers based on advanced algorithmms.

* What software will you use for your experiment?
-1.Iperf
 2.TCPDump
 3.GitBash
 4.Geni
 5.Linux router
 6.Xorp
 7.OVS switch
 8.Tshark
 9.R
 
* How will you collect the data from your experiment? Does the software that
generates data already output in a machine-friendly format? Will you need
to modify the software, or write a post-experiment processing script
to get your data into a useful format? (Manually noting down measurements
is not acceptable - your experiment data *must* be generated by a software
process.)
-We will measure packet processing time for each packet by writing a script for tcpdump. Yes, Data collected will not be in a machine friendly format.


* What kind of data analysis will you perform on your raw data?
Tcpdump output will be processed using tshark.	
We need to write post-experiment processing script in R.
-	Data analysis : IN R we will plot CDF(Cummulative Distributon function) of the delay 


* How will you test for interactions between experiment parameters?
-We will compare the statistical properties of CDF generated for each kind of router.

* How will you communicate the quantitative experiment results? Sketch any
visualization(s) that you expect to create at the end of your
experiment, showing your experiment results. Obviously you don't actually *have*
the results yet, but you should know what form they will take; so you can
draw a plot with "fake" results. Upload your sketch to any image hosting
service, and include it in this document.

- By using line plot in R.Expected plot can be viewed on th following link:

http://postimg.org/image/761vwx9dt/
Be as *specific* as you can.

