Project Proposal for EL6383
===========================



## Project idea

Write a 1-2 paragraph summary of your project. Your summary should describe:

* What topic in high speed networks is your project related to? (Your topic should be *substantially* different from the prepared labs you've already completed - "Performance of different TCP variants over networks with a high BDP" is not an acceptable topic, for example.)

* What is the goal of your experiment? Make sure to follow best practices
for setting an experiment goal, as we've discussed in class.

Be as *specific* as you can. You should have a narrow goal that dictates
a particular experiment design, not a broad open-ended evaluation.

You only have a few weeks for this project; set a realistic goal.


Our topic is to study the network protection policy. During our class hour， we studied about the 1+1, 1:1 and 1:N protection schemes. As we know 1+1 and 1:1 have
faster response to link failure but higher cost while 1:N may not response as fast as previous schemes but lower resource cost. Our goal is to verify these characteristics 
through our experiments. We need to compare the recovery time of these schemes. The lower recovery time means better ability of recovery.


## Experiment design

Describe your experiment design, including the following details (refer to lab slides for more information):

* What is the service you are going to study?
  
  Protection service 1:1, 1+1, 1:N.

* What metric(s) will you measure?
  
  The recovery time.

* What parameter(s) will you vary? In what range?
  
  With different routers we'll have different results.
  
* Describe the configuration of your experiment setting (e.g. network environment).
  
  What kind of "real" setting is this meant to represent? How do you know this experiment setting is representative? In what ways is your experiment setting *not* representative?
  We will set our network environment with the same delay and capacity. In a word, the network condition should be same. We just use different structures of protection schemes.
  Through measuring recovery time, we can get which scheme responses faster. When the network scales up, our results could be representative. If we compare these schemes in
  different environments, the results will not be representative.
  
* What software will you use for your experiment?
  
  We'll use Geni to create a network environment and run the experiment several times to collect the data that we need. And we'll use MATLAB to analyse the output data as well.

* How will you collect the data from your experiment? Does the software that
generates data already output in a machine-friendly format? Will you need
to modify the software, or write a post-experiment processing script
to get your data into a useful format? (Manually noting down measurements
is not acceptable - your experiment data *must* be generated by a software
process.)
  
  Some of the data will show directly in the output in a machine-friendly format and some data can be calculated.  

* What kind of data analysis will you perform on your raw data?
  
  We'll measure the transmission time of fixed-size packets from client to server in link failure condition and in normal condition. After that we'll analyse the time difference.
  
* How will you test for interactions between experiment parameters?
  
  With control variable method， we can find the performance of specific kind of protection scheme in different network environments(eg. capacity). Since we fixed the network 
  environment, the interactions will be eliminated.

* How will you communicate the quantitative experiment results? Sketch any
visualization(s) that you expect to create at the end of your
experiment, showing your experiment results. Obviously you don't actually *have*
the results yet, but you should know what form they will take; so you can
draw a plot with "fake" results. Upload your sketch to any image hosting
service, and include it in this document.
  
  We'll show the results in the format of tables and histograms.



Be as *specific* as you can.

