Project Proposal for EL6383
===========================



## Project idea

Write a 1-2 paragraph summary of your project. Your summary should describe:

* What topic in high speed networks is your project related to? (Your topic should be *substantially* different from the prepared labs you've already completed - "Performance of different TCP variants over networks with a high BDP" is not an acceptable topic, for example.)
Data Transfer over Over UDP and TCP.

* What is the goal of your experiment? Make sure to follow best practices
Controlling network parameters to measure and compare tcp and udp performance based on a file transfer initiated between the two.

for setting an experiment goal, as we've discussed in class.

Be as *specific* as you can. You should have a narrow goal that dictates
a particular experiment design, not a broad open-ended evaluation.

You only have a few weeks for this project; set a realistic goal.


## Experiment design

Describe your experiment design, including the following details (refer to lab slides for more information):

* What is the service you are going to study?
Data Transfer Protocol

* What metric(s) will you measure?
Metrics that we are going to use is file size, transfer time and transfer rate.

* What parameter(s) will you vary? In what range?
Parameter that we are going to vary are bandwidth, delay and packet loss rate. Bandwidth: 50k to 500k bits/s.
Delay: 0-300 ms
Packet loss rate: 0.1% to 2%

* Describe the configuration of your experiment setting (e.g. network environment).
What kind of "real" setting is this meant to represent? How do you know this experiment setting is representative? In what ways is your experiment setting *not* representative?
It represents an environment where a file is transferred over both udp and tcp link. Using geni we can set up two end nodes to transfer a file between them once as a tcp and once as a udp link.

* What software will you use for your experiment?
ipfw and FTP

* How will you collect the data from your experiment? Does the software that
generates data already output in a machine-friendly format? Will you need
to modify the software, or write a post-experiment processing script
to get your data into a useful format? (Manually noting down measurements
is not acceptable - your experiment data *must* be generated by a software
process.)
We will run ipfw to view and change the link characteristics. Also we shall use FTP (file transfer protocol) and UDT to transfer files.
We will save this raw data in text file.
Post experiment processsing script we wish to use is rstudio, To generate and compare the outputs in a graphical format.

* What kind of data analysis will you perform on your raw data?
We will perform Quantitative data analysis, so that we can compare the two data transfer protocols.

* How will you test for interactions between experiment parameters?
Changing any of the parameters will effect the metrics. For eg, If we vary the delay it will effect the transfer rate. Similarly transfer rate will also be effected by change in packet loss.
Thus we can determine the interactions between these parameters by measuring one of the metrics such as transfer rate.

* How will you communicate the quantitative experiment results? Sketch any
visualization(s) that you expect to create at the end of your
experiment, showing your experiment results. Obviously you don't actually *have*
the results yet, but you should know what form they will take; so you can
draw a plot with "fake" results. Upload your sketch to any image hosting
service, and include it in this document.

Initially we shall use output obtained from simple network configuration as a benchmark.
We will compare the outputs obtained by varying the parameters to benchmark. Comparison of FTP and UDT graphs obtained using rstudio will lead us to a conclusion for the experiment results.

Be as *specific* as you can.
