Project Proposal for EL6383
===========================


## Project idea

Write a 1-2 paragraph summary of your project. Your summary should describe:

* What topic in high speed networks is your project related to? (Your topic should be *substantially* different from the prepared labs you've already completed - "Performance of different TCP variants over networks with a high BDP" is not an acceptable topic, for example.)
Different TCP Variants in an LFN Network interrupted by UDP

* What is the goal of your experiment? Make sure to follow best practices
for setting an experiment goal, as we've discussed in class.

Be as *specific* as you can. You should have a narrow goal that dictates
a particular experiment design, not a broad open-ended evaluation.

You only have a few weeks for this project; set a realistic goal.

   ***The goal of this project is to measure throughput and resilience time of two competing 
   TCP variants (designed for LFN) when interrupted by a burst of dominating protocol like UDP.***
   
     In this project, a dumbbell network topology is chosen with a common LFN link between the two routers.
	 One side of the network has 2 sender nodes, that send competing TCP and UDP flows into the router.
     The performance of each comepting TCP flow is studied (by measuring throughput and resilience time) when interrupted by a burst of dominating protocol like UDP . 

	 
 

## Experiment design

Describe your experiment design, including the following details (refer to lab slides for more information):

* What is the service you are going to study?
 The performance of each comepting TCP flow when interrupted by a burst of dominating protocol like UDP. 

* What metric(s) will you measure?
  The throughput of each individual TCP variant and the resilience time of its throughput on introduction of interrupting flow 


* What parameter(s) will you vary? In what range?
 The parameter that is varied is the TCP variant.

* Describe the configuration of your experiment setting (e.g. network environment).
 What kind of "real" setting is this meant to represent? How do you know this experiment setting is representative? In what ways is your experiment setting *not* representative?
 
 The Dumbbell topology is used in the configuration of the experiment setting. The dumbbell topology is widely 
 considered as an acceptable representation of most modern networks where multiple nodes are connected to two 
 differnet routers, which in turn are connected by a LFN link. (1Gbps)
 
 Additonaly one node will be our TCP sender and other node will be the UDP interrupter. This mimics the situation where one tcp flow might be interrupted by massive FTPs etc. 
 Thus, we want to study how well a TCP variant performs under such conditions. 
 
* What software will you use for your experiment?
 GENI Testbeds running LINUX with custom apps to measure throughput such as tinyhttpd and iperf will be used. 

* How will you collect the data from your experiment? Does the software that
generates data already output in a machine-friendly format? Will you need
to modify the software, or write a post-experiment processing script
to get your data into a useful format? (Manually noting down measurements
is not acceptable - your experiment data *must* be generated by a software
process.)

IPERF and tinyhttpd are used to collect the data.
Yes, these softwares collect data in a machine friendly version. 

* What kind of data analysis will you perform on your raw data?

 The raw throughput data will be comapred with the data from other flows in a comparative environment
 such a graph of throughput over time or a violin graph to show distribution.

* How will you test for interactions between experiment parameters?
 The introduction of differnt competing flows would generate a change in the throughput of the 
 network which in turn would prove the interaction between the parameters. 

* How will you communicate the quantitative experiment results? Sketch any
visualization(s) that you expect to create at the end of your
experiment, showing your experiment results. Obviously you don't actually *have*
the results yet, but you should know what form they will take; so you can
draw a plot with "fake" results. Upload your sketch to any image hosting
service, and include it in this document.
Be as *specific* as you can.

[sample](http://i.imgur.com/Vu1G3To.png)

